#ifndef ACTIVEMESSAGEPARAMETERS_H_
#define ACTIVEMESSAGEPARAMETERS_H_

	enum ActiveMessageParametersEnum {
		DP_AMP_TOS_NODE_ID,
		DP_AMP_AM_ADDR,
		DP_AMP_AM_GROUP,
		DP_AMP_LAST
	};

#endif // ACTIVEMESSAGEPARAMETERS_H_
