#ifndef DEVICEPOSITIONPARAMETERS_H_
#define DEVICEPOSITIONPARAMETERS_H_

	enum DevicePositionParametersEnum {
		COORD_LATITUDE,
		COORD_LONGITUDE,
		COORD_ELEVATION,
		COORD_NORTHING,
		COORD_EASTING,
		COORD_PITCH,
		COORD_YAW,
		COORD_ROLL
	};

#endif // DEVICEPOSITIONPARAMETERS_H_
