#ifndef DEVICEUUIDPARAMETERS_H_
#define DEVICEUUIDPARAMETERS_H_

	enum DeviceUUIDParametersEnum {
		DP_UUID_BOARD,
		DP_UUID_PLATFORM,
		DP_UUID_APPLICATION,
		DP_UUID_COUNT
	};

#endif // DEVICEUUIDPARAMETERS_H_
